//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Market_Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int FatId { get; set; }
        public int ElemanId { get; set; }
        public string FatTarih { get; set; }
        public double FatFiyat { get; set; }
    
        public virtual Elemanlar Elemanlar { get; set; }
    }
}
