//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Market_Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunId { get; set; }
        public int KatId { get; set; }
        public string UrunAdi { get; set; }
        public double UrunFiyat { get; set; }
        public int UrunMiktar { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
